### ISSUE TITLE
Example not working anymore

### ISSUE THREAD

**Issue by carlesso** [oleander/capybara-js-fails#1]
Hi @oleander, thanks for the great example. Looks like that right now the example is not working, if I try to run it the test server is not fired up and the selenium instance waits until timeout. Any hint?

**Comment by oleander** [comment]
Hi,

Sorry, but I dont think I can help you with this one. It was a while ago i created this repo.
Try Stackoverflow.

**Comment by carlesso** [comment]
Thanks for the answer @oleander, don't worry, turns out it's a problem of last Firefox release and capybata webdriver. It's a very good resource anyway this repo for who want to rspec sinatra app, thanks!
